services:
  windows:
    image: dockurr/windows
    container_name: windows
    environment:
      VERSION: "2022"
      RAM_SIZE: "12G"
      CPU_CORES: "8"
      DISK_SIZE: "380G"
      DISK_SIZE2: "256G"
      DISK_SIZE3: "128G"
      USERNAME: "MasR"
      PASSWORD: "adminr"
      REGION: "id_ID"
      KEYBOARD: "en_US"
    devices:
      - /dev/kvm
      - /dev/net/tun
    cap_add:
      - NET_ADMIN
    ports:
      - 8006:8006
      - 8006:8006/tcp
      - 3389:3389/tcp
      - 3389:3389
    volumes:
      - ./windows:/storage
      - ./windows2:/storage2
      - ./windows3:/storage3
    restart: always
    stop_grace_period: 2m
